#############
#  general  #
#############

set -g base-index 1

###########
#  theme  #
###########

set -g status-style "fg=white,bg=black"

#################
#  keybindings  #
#################

# prefix
set -g prefix C-q
unbind -a -T prefix
bind C-q send-prefix

#################
#  prefix mode  #
#################

bind k select-pane -U \; switch-client -T prefix
bind j select-pane -D \; switch-client -T prefix
bind h select-pane -L \; switch-client -T prefix
bind l select-pane -R \; switch-client -T prefix
bind C-n new-window \; switch-client -T prefix
bind g switch-client -T g
bind G display-panes \; switch-client -T prefix
bind C-w switch-client -T ctrl-w
bind Z switch-client -T Z
bind Any switch-client -T prefix

############
#  g mode  #
############

bind -T g t next-window \; switch-client -T prefix
bind -T g T previous-window \; switch-client -T prefix 
bind -T g Any switch-client -T prefix

############
#  Z mode  #
############

bind -T Z C choose-client -Z
bind -T Z Q suspend-client
bind -T Z Z detach-client
bind -T Z Any switch-client -T prefix

#################
#  ctrl-w mode  #
#################
bind -T ctrl-w s split-window -v -c "#{path_current_path}" \;\
  switch-client -T prefix
bind -T ctrl-w v split-window -h -c "#{path_current_path}" \;\
  switch-client -T prefix
bind -T ctrl-w Any switch-client -T prefix
