#############
#  general  #
#############

set -g base-index 1

###########
#  theme  #
###########

set -g status-style "fg=white,bg=black"

#################
#  keybindings  #
#################

# prefix
set -g prefix C-q

#################
#  prefix mode  #
#################

bind k select-pane -U \; switch-client -T prefix
bind j select-pane -D \; switch-client -T prefix
bind h select-pane -L \; switch-client -T prefix
bind l select-pane -R \; switch-client -T prefix
bind C-n new-window \; switch-client -T prefix

bind C-w switch-client -T ctrl-w

#################
#  ctrl-w mode  #
#################
bind -T ctrl-w s split-window -v -c "#{path_current_path}" \;\
  switch-client -T prefix
bind -T ctrl-w v split-window -h -c "#{path_current_path}" \;\
  switch-client -T prefix
