#############
#  general  #
#############

set -g base-index 1

###########
#  theme  #
###########

set -g status-style "fg=white,bg=black"

#################
#  keybindings  #
#################

# prefix
set -g prefix C-q

#################
#  prefix mode  #
#################

bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R
