#!/bin/bash

link_file() {
  local dotfile_name=$1

  # TODO: validate $dotfile_name
  [[ ! -e "${HOME_DIR}/${dotfile_name}" ]] && error_setup_skip "${dotfile_name}" "Not in ${HOME_DIR}" && return

  pushd ~ >/dev/null
  # ln -s /path/to/dotfiles/home/.dotfile .dotfile
  ! ln -fns "${HOME_DIR}/${dotfile_name}" "${dotfile_name}" \
    && error_setup_skip "${dotfile_name}" "failed to link" \
    && popd >/dev/null && return # TODO: pass error message
  popd >/dev/null

  success_setup "${dotfile_name}"
}

error_exit() {
  printf '%s\n' "$1" >&2
  exit "${2:-1}"
}

success_setup() {
  echo "[$(tput -Tscreen-256color setaf 2)OK$(tput -Tscreen-256color sgr0)] $1"
}

error_setup_skip() {
  echo "[$(tput -Tscreen-256color setaf 1)NG$(tput -Tscreen-256color sgr0)] $1 ($2)"
}
