name: dotfiles CI
jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: make test
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: make
